### ISSUE TITLE
7z command

### ISSUE THREAD

**Issue by CountOmega** [siphomateke/deezer#14]
Not exactly an issue, but a question. In the `install.sh` script, the following line is invoked:

`7z x -so $pkgname-$pkgver-setup.exe "\$PLUGINSDIR/app-32.7z" > app-32.7z`
What is the \$PLUGINSDIR variable? Is it an 7z env variable? 
Any idea how I'd invoke that in a makefile?

**Comment by siphomateke** [comment]
This project is just a fork of [this Arch package](https://github.com/SibrenVasse/deezer) for Ubuntu, so questions are probably better directed there. I'm not exactly sure what the purpose of the `$PLUGINSDIR` is, but as far as I'm aware, it's to do with Electron's NSIS installer. It's not actually used on Ubuntu, but I left it in because I wasn't 100% sure.
